# Generated by Django 4.2 on 2024-09-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title_image',
            field=models.CharField(default='Untitled', max_length=30),
        ),
    ]
