# Generated by Django 4.2 on 2024-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_image_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title_image',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
