# Generated by Django 4.2 on 2024-09-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_tshirt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tshirt',
        ),
    ]
