# Generated by Django 4.2 on 2024-09-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tshirt/')),
                ('title', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('caption', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
