# Generated by Django 4.2 on 2024-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessory/')),
                ('title', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('caption', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hat/')),
                ('title', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('caption', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pants/')),
                ('title', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('caption', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoes/')),
                ('title', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('caption', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
